name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: read-all

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install PDM
        run: curl -sSL https://pdm-project.org/install-pdm.py | python -

      - name: Install dependencies
        run: |
          pdm install -d

      - name: Run tests
        run: |
          pdm run pytest tests/
